
import FiveCodMover.FiveCodMoverJFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dam
 */
public class VentanaDialogo extends javax.swing.JFrame {
    String texto;

    /**
     * Creates new form VentanaDialogo
     */
    public VentanaDialogo(String texto) {
        this.texto = texto;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        labelMinimizar2 = new javax.swing.JLabel();
        labelMaximizar2 = new javax.swing.JLabel();
        labelCerrar2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        textoCambCorrecto = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(730, 440));
        setUndecorated(true);

        jPanel6.setBackground(new java.awt.Color(140, 70, 194));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(null);

        labelMinimizar2.setBackground(new java.awt.Color(255, 255, 255));
        labelMinimizar2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        labelMinimizar2.setForeground(new java.awt.Color(92, 52, 107));
        labelMinimizar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMinimizar2.setText("-");
        labelMinimizar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizar2MouseClicked(evt);
            }
        });
        jPanel6.add(labelMinimizar2);
        labelMinimizar2.setBounds(320, 0, 30, 20);

        labelMaximizar2.setBackground(new java.awt.Color(255, 255, 255));
        labelMaximizar2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        labelMaximizar2.setForeground(new java.awt.Color(92, 52, 107));
        labelMaximizar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMaximizar2.setText("❒");
        labelMaximizar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMaximizar2MouseClicked(evt);
            }
        });
        jPanel6.add(labelMaximizar2);
        labelMaximizar2.setBounds(350, 0, 40, 30);

        labelCerrar2.setBackground(new java.awt.Color(255, 255, 255));
        labelCerrar2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelCerrar2.setForeground(new java.awt.Color(92, 52, 107));
        labelCerrar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCerrar2.setText("X");
        labelCerrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCerrar2MouseClicked(evt);
            }
        });
        jPanel6.add(labelCerrar2);
        labelCerrar2.setBounds(390, 0, 30, 30);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        textoCambCorrecto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textoCambCorrecto.setForeground(new java.awt.Color(255, 255, 255));
        textoCambCorrecto.setText(texto);

        btnAceptar.setBackground(new java.awt.Color(177, 88, 245));
        btnAceptar.setForeground(new java.awt.Color(85, 42, 117));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(textoCambCorrecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(textoCambCorrecto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelMinimizar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizar2MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);

    }//GEN-LAST:event_labelMinimizar2MouseClicked

    private void labelMaximizar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMaximizar2MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(this.MAXIMIZED_BOTH);
        

    }//GEN-LAST:event_labelMaximizar2MouseClicked

    private void labelCerrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCerrar2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_labelCerrar2MouseClicked

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged
        // TODO add your handling code here:
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
    }//GEN-LAST:event_jPanel6MouseDragged

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
        FiveCodMoverJFrame.MousePressed(evt);
    }//GEN-LAST:event_jPanel6MousePressed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new VentanaPrincipal().setVisible(true);
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelCerrar2;
    private javax.swing.JLabel labelMaximizar2;
    private javax.swing.JLabel labelMinimizar2;
    private javax.swing.JLabel textoCambCorrecto;
    // End of variables declaration//GEN-END:variables
}
